language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"

# command to run tests fast and accept failures.
jobs:
  fast_finish: true
  allow_failures:
    - python: 3.6

# command to install dependencies.
install:
  - pip install .
  - pip install -r requirements-test.txt

# Git clone depth
# By default Travis CI clones repositories to a depth of 50 commits. Using a depth of 1 makes this step a bit faster.
git:
  depth: 1

# command to run tests
script: nosetests
